"""01 class User

Revision ID: d61c3d71fd57
Revises: be87b697304d
Create Date: 2023-03-07 11:15:23.198913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61c3d71fd57'
down_revision = 'be87b697304d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
